const panelToggle = (panel: string, label: string, content: string) => `<button class="panel-toggle" data-panel="${panel}" aria-expanded="true" aria-controls="${content}" aria-label="Свернуть ${label}" title="Свернуть ${label}">−</button>`;
export const template = `
<header class="topbar"><a class="brand" href="#" aria-label="Data Factory"><span class="brand-icon">◇</span><span>DATA<span class="brand-light">FACTORY</span><small>VISUAL PROGRAMMING IDE</small></span></a><div class="top-divider"></div><div class="project-identity"><small id="workspace-kind">PROJECT</small><strong id="project-name">Blank Factory.df</strong><span id="save-status">● Saved</span></div><div class="top-actions"><button data-action="new-project">New Project</button><button data-action="open-project">Open Project</button><button data-action="tutorial">Tutorial</button><button data-action="examples">Examples</button><button data-action="help" class="icon-button" title="Справка">?</button></div></header>
<section class="levelbar"><div class="level-heading"><div><small id="level-topic">GRAPH WORKSPACE</small><h1 id="level-name">Blank Factory</h1></div></div><div class="execution-controls"><span id="mode" class="mode-pill">EDIT</span><button data-action="edit" id="edit-btn">■ Stop</button><button data-action="run" id="run-btn" class="primary">▶ RUN</button><button data-action="step" id="step-btn">Step</button><select id="speed" aria-label="Скорость выполнения"><option value="0.25">0.25x</option><option value="0.5">0.5x</option><option value="1" selected>1x</option><option value="2">2x</option><option value="4">4x</option><option value="0">Instant</option></select></div></section>
<main class="workspace"><aside class="palette"><div class="panel-heading"><h2>NODE PALETTE</h2><span id="machine-count" class="muted"></span>${panelToggle('palette', 'Node Palette', 'palette-content')}</div><div id="palette-content"><p class="panel-caption">Нажмите или перетащите ноду на граф</p><div id="palette-list"></div></div></aside>
<section class="workbench"><div class="canvas-toolbar"><div class="toolbar-label">GRAPH CANVAS <span id="graph-count"></span></div><div class="graph-actions"><button data-action="undo" id="undo-btn" title="Undo">↶</button><button data-action="redo" id="redo-btn" title="Redo">↷</button><span class="toolbar-separator"></span><button data-action="export" title="Export graph">Export</button><button data-action="import" title="Import graph">Import</button><button data-action="clear" title="Clear graph">Clear</button></div>${panelToggle('graph', 'Graph Canvas', 'game')}</div><div id="game" aria-label="Граф программы"></div><div id="empty-state"><div class="empty-eyebrow">BLANK FACTORY</div><div class="ghost-flow"><span>→<small>SOURCE</small></span><i>───</i><span>□<small>OUTPUT</small></span></div><h2>Соберите программу из нод</h2><p>Добавьте ноды слева, соедините порты и нажмите RUN.</p><span class="empty-shortcut">PROJECT → GRAPH → NODES → RUNTIME</span></div><div id="tutorial" class="tutorial" hidden></div><div class="canvas-bottom"><span>Перемещение: правая кнопка мыши · Масштаб: колесо</span><div><button data-action="zoom-out">−</button><button data-action="fit">Fit</button><button data-action="zoom-in">+</button></div></div></section>
<aside class="inspector"><div class="panel-heading"><h2>INSPECTOR</h2><span class="tiny-tag">LIVE</span>${panelToggle('inspector', 'Inspector', 'inspector-content')}</div><div id="inspector-content"></div></aside></main>
<section class="bottom-panel"><nav class="tabs"><button data-tab="console" class="active">Console</button><button data-tab="variables">Variables</button><button data-tab="execution">Execution</button><button data-tab="errors">Errors</button><button data-tab="profiler">Profiler</button><button data-tab="code">Code View</button><button data-tab="tests" id="tests-tab" hidden>Tests <span id="test-count"></span></button><div class="tab-actions"><span id="stats-line"></span><button data-action="check" id="check-btn" hidden>Check tests</button>${panelToggle('bottom', 'нижнюю панель', 'tab-content')}</div></nav><div id="tab-content"></div></section>
<footer class="statusbar"><span id="status-message" role="status" aria-live="polite"></span><label id="input-label">Input JSON <input id="runtime-input" value="42" aria-label="Входное значение JSON" /></label></footer>
<dialog id="modal"><div class="modal-top"><h2 id="modal-title"></h2><button data-action="close-modal" class="icon-button" aria-label="Закрыть">×</button></div><div id="modal-content"></div></dialog><input type="file" id="import-file" accept="application/json,.json,.df" hidden />`;
