import type { DataValue, Level, LevelTest } from '../../core/types';
const cases = (values: [DataValue, DataValue][]): LevelTest[] => values.map(([input, expected], i) => ({ input, expected, hidden: i >= 3 }));
const base = ['source', 'output'];
export const levels: Level[] = [
  { id: 'first-signal', name: 'Первый сигнал', topic: '01 / ОСНОВЫ ПОТОКА', description: 'Каждая программа начинается с данных. Постройте самую маленькую фабрику: передайте входное значение в Output без изменений.', hint: 'Добавьте Source и Output. Потяните от зелёного порта справа к порту слева.', inputType: 'number', availableMachines: base, tests: cases([[42, 42], [7, 7], [-3, -3], [0, 0], [128, 128]]), medals: { machines: 2, operations: 10, ticks: 25 }, tutorial: [
    { text: 'Перетащите SOURCE из каталога на поле.', condition: 'machine', machineType: 'source' },
    { text: 'Добавьте OUTPUT — приёмник результата.', condition: 'machine', machineType: 'output' },
    { text: 'Потяните от правого порта SOURCE к левому порту OUTPUT. Можно нажать на порты по очереди.', condition: 'connection' },
    { text: 'Нажмите RUN, проследите за пакетом и проверьте все тесты.', condition: 'completed' },
  ] },
  { id: 'double', name: 'Удвоение', topic: '02 / АРИФМЕТИКА', description: 'Умножьте каждое входное число на 2. Подключите число и константу к двум входам Math.', hint: 'Source → Math A; Constant(2) → Math B. У Math выберите *.', inputType: 'number', availableMachines: [...base, 'constant', 'arithmetic'], tests: cases([[5, 10], [12, 24], [-3, -6], [0, 0], [1.5, 3]]), medals: { machines: 4, operations: 20, ticks: 70 } },
  { id: 'plus-ten', name: 'Запас мощности', topic: '03 / КОНСТАНТЫ', description: 'Прибавьте 10 к входному числу. Измените параметры машин в инспекторе справа.', hint: 'У Constant значение 10, у Math операция +.', inputType: 'number', availableMachines: [...base, 'constant', 'arithmetic'], tests: cases([[5, 15], [12, 22], [-3, 7], [-10, 0], [0, 10]]), medals: { machines: 4, operations: 20, ticks: 70 } },
  { id: 'greater-ten', name: 'Порог допуска', topic: '04 / СРАВНЕНИЯ', description: 'Верните true, если входное число строго больше 10, иначе false. Равенство порогу не считается.', hint: 'Source → Compare A; Constant(10) → Compare B. Операция >.', inputType: 'number', availableMachines: [...base, 'constant', 'comparator'], tests: cases([[20, true], [5, false], [10, false], [-2, false], [10.1, true]]), medals: { machines: 4, operations: 20, ticks: 70 } },
  { id: 'even', name: 'Чёткий ритм', topic: '05 / КОМПОЗИЦИЯ', description: 'Определите, чётное ли число. Остаток от деления чётного числа на 2 равен нулю.', hint: 'Сначала Math с % и Constant(2), затем Compare с == и Constant(0).', inputType: 'number', availableMachines: [...base, 'constant', 'arithmetic', 'comparator'], tests: cases([[8, true], [7, false], [0, true], [-4, true], [-3, false], [101, false]]), medals: { machines: 6, operations: 36, ticks: 130 } },
  { id: 'reassemble', name: 'По частям', topic: '06 / ПОТОКИ', description: 'Разберите строку на символы и соберите её обратно. Проследите за отдельными пакетами между Split и Join.', hint: 'Source → Split → Join (string) → Output. Join ждёт конца потока.', inputType: 'string', availableMachines: [...base, 'split', 'join', 'queue'], tests: cases([['CAT', 'CAT'], ['DATA', 'DATA'], ['A B', 'A B'], ['', ''], ['🚀Я', '🚀Я']]), medals: { machines: 4, operations: 20, ticks: 115 } },
  { id: 'reverse-string', name: 'Обратный поток', topic: '07 / СТЕК', description: 'Разверните строку. Stack выдаёт элементы в обратном порядке: последний вошёл — первый вышел.', hint: 'Source → Split → Stack → Join → Output. Для пустой строки результат тоже пустая строка.', inputType: 'string', availableMachines: [...base, 'split', 'stack', 'queue', 'join'], tests: cases([['HELLO', 'OLLEH'], ['CAT', 'TAC'], ['PROGRAM', 'MARGORP'], ['', ''], ['A', 'A'], ['🚀Я', 'Я🚀']]), medals: { machines: 5, operations: 30, ticks: 240 } },
  { id: 'positive', name: 'Развилка', topic: '08 / УСЛОВИЯ', description: 'Для числа больше нуля верните "POSITIVE", для остальных — "NEGATIVE". Направьте данные по правильной ветке.', hint: 'Сравните Source с 0. Source также идёт в Branch data, Compare — в condition. Выходы Branch подключите к trigger двух Constant со строками; обе константы — в Output. Ноль → "NEGATIVE".', inputType: 'number', availableMachines: [...base, 'constant', 'comparator', 'branch', 'memory'], tests: cases([[5, 'POSITIVE'], [-2, 'NEGATIVE'], [0, 'NEGATIVE'], [0.1, 'POSITIVE'], [-100, 'NEGATIVE']]), medals: { machines: 7, operations: 35, ticks: 155 } },
  { id: 'filter', name: 'Контроль качества', topic: '09 / ФИЛЬТРАЦИЯ', description: 'Оставьте в массиве только числа строго больше 10. Порядок подходящих элементов должен сохраниться.', hint: 'Split → Compare A и Filter data. Constant(10) → Compare B; Compare(>) → Filter condition. Filter → Join в режиме array → Output.', inputType: 'array', availableMachines: [...base, 'split', 'constant', 'comparator', 'filter', 'join', 'queue'], tests: cases([[[2, 15, 5, 30], [15, 30]], [[10, 11, 12], [11, 12]], [[-2, 0, 8], []], [[], []], [[20, 20, -1, 100], [20, 20, 100]]]), medals: { machines: 7, operations: 35, ticks: 250 } },
  { id: 'palindrome', name: 'Зеркальная линия', topic: '10 / АЛГОРИТМЫ', description: 'Проверьте, читается ли строка одинаково в обе стороны. Сравните исходное значение с развёрнутым.', hint: 'Сделайте фабрику разворота. Исходный Source подключите ещё и к Compare A, результат Join — в B. Выберите ==. Пустая строка считается палиндромом.', inputType: 'string', availableMachines: [...base, 'split', 'stack', 'queue', 'join', 'comparator', 'memory'], tests: cases([['LEVEL', true], ['RADAR', true], ['HELLO', false], ['', true], ['A', true], ['AB', false], ['АБА', true]]), medals: { machines: 6, operations: 42, ticks: 360 } },
  { id: 'absolute', name: 'Модуль числа', topic: '11 / ЧИСЛА', description: 'Верните модуль входного числа — его расстояние до нуля без знака. Модуль отрицательного числа равен ему без минуса.', hint: 'Source → ABS → Output. ABS превращает −5 в 5, −0.5 в 0.5, а 0 оставляет нулём.', inputType: 'number', availableMachines: [...base, 'abs'], tests: cases([[-5, 5], [3, 3], [-0.5, 0.5], [0, 0], [-12.5, 12.5]]), medals: { machines: 3, operations: 15, ticks: 45 }, tutorial: [
    { text: 'Перетащите SOURCE из каталога на поле.', condition: 'machine', machineType: 'source' },
    { text: 'Добавьте ABS — модуль числа.', condition: 'machine', machineType: 'abs' },
    { text: 'Добавьте OUTPUT — приёмник результата.', condition: 'machine', machineType: 'output' },
    { text: 'Соедините Source → ABS → Output.', condition: 'connection' },
    { text: 'Нажмите RUN и проверьте все тесты.', condition: 'completed' },
  ] },
  { id: 'negate-sign', name: 'Смена знака', topic: '12 / ЧИСЛА', description: 'Поменяйте знак числа: положительное станет отрицательным, отрицательное — положительным.', hint: 'Source → NEGATE → Output. NEGATE меняет знак каждого числа; ноль не меняется.', inputType: 'number', availableMachines: [...base, 'negate'], tests: cases([[5, -5], [-2, 2], [0, -0], [1.5, -1.5], [-100, 100]]), medals: { machines: 3, operations: 15, ticks: 45 }, tutorial: [
    { text: 'Перетащите SOURCE из каталога на поле.', condition: 'machine', machineType: 'source' },
    { text: 'Добавьте NEGATE — смену знака.', condition: 'machine', machineType: 'negate' },
    { text: 'Добавьте OUTPUT — приёмник результата.', condition: 'machine', machineType: 'output' },
    { text: 'Соедините Source → NEGATE → Output.', condition: 'connection' },
    { text: 'Нажмите RUN и проверьте все тесты.', condition: 'completed' },
  ] },
  { id: 'not-above-ten', name: 'Не больше десяти', topic: '13 / ЛОГИКА', description: 'Верните true, если число меньше или равно 10, иначе false. Инвертируйте результат сравнения с порогом.', hint: 'Source → Compare A; Constant(10) → Compare B. Операция >. Затем NOT инвертирует ответ: больше 10 станет false.', inputType: 'number', availableMachines: [...base, 'constant', 'comparator', 'not'], tests: cases([[9, true], [10, true], [11, false], [-5, true], [10.01, false]]), medals: { machines: 5, operations: 25, ticks: 85 }, tutorial: [
    { text: 'Перетащите SOURCE из каталога на поле.', condition: 'machine', machineType: 'source' },
    { text: 'Добавьте CONSTANT — порог 10.', condition: 'machine', machineType: 'constant' },
    { text: 'Добавьте COMPARE и выберите операцию >.', condition: 'machine', machineType: 'comparator' },
    { text: 'Добавьте NOT — логическое отрицание.', condition: 'machine', machineType: 'not' },
    { text: 'Добавьте OUTPUT — приёмник результата.', condition: 'machine', machineType: 'output' },
    { text: 'Соедините Source → Compare A, Constant(10) → Compare B, Compare → NOT → Output.', condition: 'connection' },
    { text: 'Нажмите RUN и проверьте все тесты.', condition: 'completed' },
  ] },
  { id: 'string-length', name: 'Длина строки', topic: '14 / СТРОКИ', description: 'Верните количество Unicode-символов входной строки. Каждый символ считается один раз.', hint: 'Source → LENGTH → Output. Символ 🚀 считается одним символом, пустая строка даёт 0.', inputType: 'string', availableMachines: [...base, 'length'], tests: cases([['HELLO', 5], ['', 0], ['АБВ', 3], ['🚀Я', 2], ['DATA FACTORY', 12]]), medals: { machines: 3, operations: 15, ticks: 45 }, tutorial: [
    { text: 'Перетащите SOURCE из каталога на поле.', condition: 'machine', machineType: 'source' },
    { text: 'Добавьте LENGTH — длину строки.', condition: 'machine', machineType: 'length' },
    { text: 'Добавьте OUTPUT — приёмник результата.', condition: 'machine', machineType: 'output' },
    { text: 'Соедините Source → LENGTH → Output.', condition: 'connection' },
    { text: 'Нажмите RUN и проверьте все тесты.', condition: 'completed' },
  ] },
  { id: 'exclaim', name: 'Слияние строк', topic: '15 / СТРОКИ', description: 'Соедините входную строку с константой: добавьте восклицательный знак в конец.', hint: 'Source → CONCAT (вход A); Constant("!") → CONCAT (вход B); CONCAT → Output.', inputType: 'string', availableMachines: [...base, 'constant', 'concat'], tests: cases([['HELLO', 'HELLO!'], ['', '!'], ['АБ', 'АБ!'], ['🚀', '🚀!'], ['TEST', 'TEST!']]), medals: { machines: 4, operations: 20, ticks: 65 }, tutorial: [
    { text: 'Перетащите SOURCE из каталога на поле.', condition: 'machine', machineType: 'source' },
    { text: 'Добавьте CONSTANT — суффикс "!".', condition: 'machine', machineType: 'constant' },
    { text: 'Добавьте CONCAT — соединение строк.', condition: 'machine', machineType: 'concat' },
    { text: 'Добавьте OUTPUT — приёмник результата.', condition: 'machine', machineType: 'output' },
    { text: 'Соедините Source → Concat A, Constant("!") → Concat B, Concat → Output.', condition: 'connection' },
    { text: 'Нажмите RUN и проверьте все тесты.', condition: 'completed' },
  ] },
  { id: 'array-sum', name: 'Сумма массива', topic: '16 / МАССИВЫ', description: 'Сложите все числа входного массива. Пустой массив даёт 0.', hint: 'Source → SUM → Output. SUM принимает один массив и возвращает одно число.', inputType: 'array', availableMachines: [...base, 'sum'], tests: cases([[[2, 3, 4], 9], [[-1, 5], 4], [[], 0], [[10], 10], [[1.5, 2.5], 4]]), medals: { machines: 3, operations: 15, ticks: 45 }, tutorial: [
    { text: 'Перетащите SOURCE из каталога на поле.', condition: 'machine', machineType: 'source' },
    { text: 'Добавьте SUM — сумму массива.', condition: 'machine', machineType: 'sum' },
    { text: 'Добавьте OUTPUT — приёмник результата.', condition: 'machine', machineType: 'output' },
    { text: 'Соедините Source → SUM → Output.', condition: 'connection' },
    { text: 'Нажмите RUN и проверьте все тесты.', condition: 'completed' },
  ] },
  { id: 'sort-ascending', name: 'Сортировка', topic: '17 / МАССИВЫ', description: 'Отсортируйте числа массива по возрастанию. Порядок задаётся в Inspector.', hint: 'Source → SORT → Output. У SORT выберите порядок ascending.', inputType: 'array', availableMachines: [...base, 'sort'], tests: cases([[[3, 1, 2], [1, 2, 3]], [[5, 5, 1], [1, 5, 5]], [[], []], [[-2, 10, -2], [-2, -2, 10]], [[7], [7]]]), medals: { machines: 3, operations: 15, ticks: 45 }, tutorial: [
    { text: 'Перетащите SOURCE из каталога на поле.', condition: 'machine', machineType: 'source' },
    { text: 'Добавьте SORT — сортировку чисел.', condition: 'machine', machineType: 'sort' },
    { text: 'Добавьте OUTPUT — приёмник результата.', condition: 'machine', machineType: 'output' },
    { text: 'Соедините Source → SORT → Output.', condition: 'connection' },
    { text: 'Нажмите RUN и проверьте все тесты.', condition: 'completed' },
  ] },
  { id: 'unique-elements', name: 'Уникальность', topic: '18 / МАССИВЫ', description: 'Удалите повторяющиеся элементы массива, сохранив порядок первых вхождений.', hint: 'Source → UNIQUE → Output. UNIQUE сравнивает по содержимому: 1 и true — разные значения.', inputType: 'array', availableMachines: [...base, 'unique'], tests: cases([[[1, 2, 2, 3], [1, 2, 3]], [[5, 5, 5], [5]], [[1, true, 1, '1', true], [1, true, '1']], [[], []], [[1, [2], [2], 1], [1, [2]]]]), medals: { machines: 3, operations: 15, ticks: 45 }, tutorial: [
    { text: 'Перетащите SOURCE из каталога на поле.', condition: 'machine', machineType: 'source' },
    { text: 'Добавьте UNIQUE — удаление повторов.', condition: 'machine', machineType: 'unique' },
    { text: 'Добавьте OUTPUT — приёмник результата.', condition: 'machine', machineType: 'output' },
    { text: 'Соедините Source → UNIQUE → Output.', condition: 'connection' },
    { text: 'Нажмите RUN и проверьте все тесты.', condition: 'completed' },
  ] },
  { id: 'average', name: 'Среднее арифметическое', topic: '19 / КОМПОЗИЦИЯ', description: 'Найдите среднее чисел массива: разделите сумму всех элементов на их количество.', hint: 'Source → SUM и LENGTH. Оба результата → MATH с операцией деления, затем → Output.', inputType: 'array', availableMachines: [...base, 'sum', 'length', 'arithmetic'], tests: cases([[[2, 4], 3], [[1, 2, 3], 2], [[-2, 2], 0], [[1, 2], 1.5], [[10], 10]]), medals: { machines: 5, operations: 25, ticks: 100 }, tutorial: [
    { text: 'Перетащите SOURCE из каталога на поле.', condition: 'machine', machineType: 'source' },
    { text: 'Добавьте SUM — сумму массива.', condition: 'machine', machineType: 'sum' },
    { text: 'Добавьте LENGTH — число элементов.', condition: 'machine', machineType: 'length' },
    { text: 'Добавьте MATH и выберите операцию деления /.', condition: 'machine', machineType: 'arithmetic' },
    { text: 'Добавьте OUTPUT — приёмник результата.', condition: 'machine', machineType: 'output' },
    { text: 'Соедините Source с SUM и LENGTH, оба результата — в MATH, а MATH — в Output.', condition: 'connection' },
    { text: 'Нажмите RUN и проверьте все тесты.', condition: 'completed' },
  ] },
  { id: 'reverse-array', name: 'Обратный массив', topic: '20 / АЛГОРИТМЫ', description: 'Разверните порядок элементов массива: последний элемент станет первым, первый — последним.', hint: 'Source → Split → Stack → Join. У Join выберите режим array. Stack выдаёт элементы в обратном порядке (LIFO).', inputType: 'array', availableMachines: [...base, 'split', 'stack', 'queue', 'join'], tests: cases([[[1, 2, 3], [3, 2, 1]], [[], []], [['a', 'b'], ['b', 'a']], [[42], [42]], [[true, false], [false, true]]]), medals: { machines: 5, operations: 25, ticks: 100 }, tutorial: [
    { text: 'Перетащите SOURCE из каталога на поле.', condition: 'machine', machineType: 'source' },
    { text: 'Добавьте SPLIT — разбивает массив на элементы.', condition: 'machine', machineType: 'split' },
    { text: 'Добавьте STACK — разворачивает поток.', condition: 'machine', machineType: 'stack' },
    { text: 'Добавьте JOIN и выберите режим array.', condition: 'machine', machineType: 'join' },
    { text: 'Добавьте OUTPUT — приёмник результата.', condition: 'machine', machineType: 'output' },
    { text: 'Соедините Source → Split → Stack → Join → Output.', condition: 'connection' },
    { text: 'Нажмите RUN и проверьте все тесты.', condition: 'completed' },
  ] },
];
